// Generated by Selenium IDE
package tests;
import org.junit.AfterClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CicekFiltreTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\egeme\\Downloads\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cicekFiltreTest1() throws InterruptedException {

    // CicekSepeti.com opens
    driver.get("https://www.ciceksepeti.com/");
    //Adjust browser window
    driver.manage().window().setSize(new Dimension(1050, 708));
    // Location select pop-up closes
    driver.findElement(By.xpath("//body/main[1]/div[1]/div[1]/div[1]/div[1]/a[1]/span[1]")).click();
    // Clicks cicek button
    driver.findElement(By.linkText("ÇİÇEK")).click();
    Thread.sleep(2000);
    // Chooses  filter
    driver.findElement(By.linkText("Renk")).click();
    // Chooses Color
    driver.findElement(By.cssSelector(".dropdown:nth-child(4) .filter__dropdown-list:nth-child(2) > .filter__dropdown-label")).click();
    // Applies Filter
    driver.findElement(By.cssSelector(".open .js-apply-filter-group-button")).click();
    // If the "Temizle" element appears, Test OK ! If not test fails
    assertThat(driver.findElement(By.xpath("//body/main[1]/div[1]/div[1]/div[2]/div[2]/a[1]")).getText(), is("Temizle"));
  }
  @Test
  public void cicekFiltreTest2() throws InterruptedException {
    // Test name: CicekFiltreTemizle
    // Step # | name | target | value | comment
    // 1 | open | https://www.ciceksepeti.com/cicek?df=151 |  |
    driver.get("https://www.ciceksepeti.com/cicek?df=151");
    driver.manage().window().setSize(new Dimension(1050, 708));
    // Location Select pop-up closes
    driver.findElement(By.xpath("//body/div[5]/div[1]/div[1]/div[1]/a[1]/span[1]")).click();
    // Clicks on "Temizle" button to clear Filters
    driver.findElement(By.xpath("//body/main[1]/div[1]/div[1]/div[2]/div[2]/a[1]")).click();
    {
      // If, Automation cannot find "Temizle" button that means its successfuly cleared
      List<WebElement> elements = driver.findElements(By.xpath("//body/main[1]/div[1]/div[1]/div[2]/div[2]/a[1]"));
      assert(elements.size() == 0);
    }
  }
  @AfterClass
  public static void afterTest(){
    System.out.println("Test performed");
  }
}
