# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDealoftheDay():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(
            executable_path=r"C:\Users\egeme\pythonProject\chromedriver.exe")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_dealoftheDay(self):
        self.driver.get("https://www.amazon.com/")
        self.driver.set_window_size(1366, 720)
        time.sleep(7)
        self.driver.find_element(By.XPATH, "/html[1]/body[1]/div[1]/header[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[3]/span[1]/span[1]/input[1]").click()
        self.driver.find_element(By.LINK_TEXT, "Today\'s Deals").click()
        assert self.driver.find_element(By.XPATH,
                                        "//body/div[@id=\'a-page\']/div[10]/div[1]/div[1]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/span[1]").text == "DEAL OF THE DAY"

    def test_shipToTurkey(self):
        self.driver.get("https://www.amazon.com/")
        self.driver.set_window_size(1366, 720)
        self.driver.find_element(By.ID, "twotabsearchtextbox").click()
        self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys("laptop")
        self.driver.find_element(By.ID, "twotabsearchtextbox").send_keys(Keys.ENTER)
        WebDriverWait(self.driver, 1).until(expected_conditions.visibility_of_element_located((By.XPATH,
                                                                                                 "//body/div[@id=\'a-page\']/div[@id=\'search\']/div[1]/div[1]/div[1]/span[3]/div[2]/div[2]/div[1]/span[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/span[1]")))

